- name: Setup user
  ansible.builtin.import_tasks: user.yaml

- name: Setup directories
  ansible.builtin.import_tasks: directories.yaml

- name: Generate config and manage logs
  ansible.builtin.import_tasks: config.yaml