Vagrant.configure("2") do |config|

  config.vm.define "web" do |web|
    web.vm.box      = "generic/ubuntu2004"
    web.vm.hostname = "web"

    web.vm.provider "hyperv" do |h|
      h.memory         = 1024
      h.cpus           = 1
    end
  end

  config.vm.define "db" do |db|
    db.vm.box      = "generic/ubuntu2004"
    db.vm.hostname = "db"

    db.vm.provider "hyperv" do |h|
      h.memory         = 1024
      h.cpus           = 1
    end
  end

end
