postgresql_databases:
  - name: FirstDB
  - name: SecondDB

postgresql_users:
  - name: "Jon Doe"
    password: "{{ vault_postgres_jon_doe_password }}"
    db: FirstDB

  - name: "Jane Doe"
    password: "{{ vault_postgres_jane_doe_password }}"
    db: SecondDB