- name: Ansible-lab
  hosts: all
  tags: config

  pre_tasks:
    - name: Load environment variables
      ansible.builtin.include_vars:
        file: "vars/{{ app_env }}.yaml"

  roles:
    - webserver

- name: Setup webserver
  hosts: webservers
  become: true
  tags: nginx

  roles:
    - nginx

- name: Setup database
  hosts: databases
  become: true
  tags: postgresql

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600

  roles:
    - geerlingguy.postgresql