- name: Ansible-lab
  hosts: all

  pre_tasks:
    - name: Load environment variables
      ansible.builtin.include_vars:
        file: "vars/{{ app_env }}.yaml"

  roles:
    - webserver

- name: Setup webserver
  hosts: webservers
  become: true

  roles:
    - nginx